### ISSUE TITLE
Create a Sketch cheatsheet

### ISSUE THREAD

**Issue by kwm14** [canonical-web-and-design/design-vanilla-framework#414]

**Comment by kwm14** [comment]
Created a cheatsheet guide based on @lyubomir-popov spacing variables [document](https://docs.google.com/spreadsheets/d/1psInYHEOdSaDHaHeARlryBA3PprbuBS2oT1fS5_lmK4/edit#gid=0), which highlights components affected when changing the horizontal or vertical spacing.

@spencerbygraves @lyubomir-popov ready for review 👍 

![001-spacong-variable-cheatsheet](https://user-images.githubusercontent.com/17748020/59344413-f4079000-8d05-11e9-8989-82d84cd1f0af.png)

**Comment by lyubomir-popov** [comment]
@kwm14 @spencerbygraves thanks Karlos, very nice presentation. Some comments, all of these are my fault for not clarifying initially. Sorry about that.

• px values are only true when 1rem == 16px, which changes on bigger screen to 18 and everything adjusts accordingly. So I think it's probably best to not use units, and shift the focus to things that are same. This is why I intended to use colours instead of numbers, so it is true in all cases.

• It should work as a flowchart - or a steps of decisions for a designer mocking up, or a developer implementing a mockup of a new component. Something like this:

1. Am I dealing with vertical or horizontal space? 
• vertical -> look at variables starting with $spv-
• horizontal -> $sph

2. Inside or outside? 
• -inner
• -outer

3. Which elements should it match? I.e., if put next to something , it should be constructed similarly. Usually this has to do with amount of content inside it, is it one line / multiple lines, etc.

4. In the case of vertical spacing, should it align with free flowing text (like a button often has to)? Or should it be symmetrical top/bottom, like navs, tastrips etc that do not sit next to free flowing text?
• yes: use var with nudge compensation compensation
• no: use vars used in menu, tabstrip etc.


And finally, we should make sure we don't use this decoratively - as in the orange strip, where the value 472px is not meaningful. It depends on the amount of text, and it is not based on any of the spacing variables used in vanilla. This is because things like that undermine the impression of strong logic behind every decision, and could tempt developers to disregard these as just a designer fanciness. We want this to be a commone language between design / development, so either side can reviw and question the correctness of any decisions, or spot errors creeping in. And most importantly, make these vars familiar enough to devs, so they don't feel tempted to just hardcode things like this:

![image](https://user-images.githubusercontent.com/2741678/59348062-1c938800-8d0e-11e9-9d4d-ea8e6bcd1382.png)

**Comment by kwm14** [comment]
@lyubomir-popov thanks 😄 no worries at all. Let's sync up and discuss tomorrow when back I'm back in the office tomorrow 👍

**Comment by cristinadresch** [comment]
@kwm14 Lyubo will be off for 2 more weeks, should we leave this one on blocked for now or can we progress on it without him?

**Comment by kwm14** [comment]
@cristinadresch Ok cool. I will move it out of the iteration and speak with him once back in the office 👍

**Comment by anthonydillon** [comment]
@lyubomir-popov is this still something you want to do? I wonder if you can keep it up to date with changes in the codebase?

**Comment by lyubomir-popov** [comment]
Yes, definitely still valid, rather large though so I need to finish the modular table before starting this.

**Comment by bartaz** [comment]
We are not doing it.
